#!/bin/bash
#
# Module: APT Sources Configuration
# Purpose: Switch APT sources to Tsinghua mirror using DEB822 format
#

# Module configuration
readonly MODULE_NAME="apt-sources"
readonly SOURCES_FILE="/etc/apt/sources.list.d/debian.sources"
readonly BACKUP_FILE="${SOURCES_FILE}.bak"
readonly OLD_SOURCES_FILE="/etc/apt/sources.list"

# Check if we're on Debian
check_debian() {
    if ! command -v lsb_release >/dev/null 2>&1; then
        log_warn "lsb_release not found, installing lsb-release package"
        apt-get update -qq && apt-get install -y lsb-release
    fi

    local distro=$(lsb_release -si 2>/dev/null)
    if [[ "$distro" != "Debian" ]]; then
        log_warn "Not running on Debian (detected: $distro), skipping APT sources configuration"
        return 1
    fi
    return 0
}

# Get Debian version codename
get_debian_codename() {
    lsb_release -sc 2>/dev/null || echo "bookworm"
}

# Backup existing sources
backup_sources() {
    if [[ -f "$SOURCES_FILE" ]] && [[ ! -f "$BACKUP_FILE" ]]; then
        log_info "Backing up existing sources file"
        cp "$SOURCES_FILE" "$BACKUP_FILE"
    fi

    # Also backup old format sources.list if it exists
    if [[ -f "$OLD_SOURCES_FILE" ]] && [[ ! -f "${OLD_SOURCES_FILE}.bak" ]]; then
        log_info "Backing up old format sources.list"
        cp "$OLD_SOURCES_FILE" "${OLD_SOURCES_FILE}.bak"
    fi
}

# Create DEB822 format sources file
create_deb822_sources() {
    local codename=$(get_debian_codename)
    log_info "Configuring APT sources for Debian $codename using Tsinghua mirror"

    cat > "$SOURCES_FILE" << EOF
# Debian $codename - Tsinghua Mirror (DEB822 format)
# Generated by homelab-platform baseline initialization
# $(date)

Types: deb
URIs: https://mirrors.tuna.tsinghua.edu.cn/debian
Suites: $codename $codename-updates
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

Types: deb
URIs: https://mirrors.tuna.tsinghua.edu.cn/debian-security
Suites: $codename-security
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

Types: deb
URIs: https://mirrors.tuna.tsinghua.edu.cn/debian
Suites: $codename-backports
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
EOF

    log_success "Created DEB822 sources file: $SOURCES_FILE"
}

# Disable old sources.list if it exists
disable_old_sources() {
    if [[ -f "$OLD_SOURCES_FILE" ]] && [[ -s "$OLD_SOURCES_FILE" ]]; then
        log_info "Disabling old format sources.list"
        # Comment out all non-comment lines
        sed -i 's/^[^#]/# &/' "$OLD_SOURCES_FILE"
        log_info "Old sources.list has been commented out"
    fi
}

# Test APT sources
test_apt_sources() {
    log_info "Testing APT sources configuration"

    if apt-get update -qq 2>/dev/null; then
        log_success "APT sources are working correctly"

        # Verify we're using Tsinghua mirror
        if apt policy 2>/dev/null | grep -q "mirrors.tuna.tsinghua.edu.cn"; then
            log_success "Confirmed using Tsinghua mirror"
        else
            log_warn "Tsinghua mirror not detected in apt policy output"
        fi
    else
        log_error "APT update failed, sources configuration may be incorrect"
        return 1
    fi
}

# Check if sources are already configured
is_sources_configured() {
    [[ -f "$SOURCES_FILE" ]] && grep -q "mirrors.tuna.tsinghua.edu.cn" "$SOURCES_FILE"
}

# Main module execution
main() {
    log_info "Starting APT sources configuration"

    # Check if we're on Debian
    if ! check_debian; then
        return 0
    fi

    # Check if already configured
    if is_sources_configured; then
        log_info "APT sources already configured with Tsinghua mirror"
        return 0
    fi

    # Backup existing configuration
    backup_sources

    # Create new DEB822 sources
    create_deb822_sources

    # Disable old sources.list
    disable_old_sources

    # Test the configuration
    if test_apt_sources; then
        log_success "APT sources configuration completed successfully"
    else
        log_error "APT sources configuration failed"
        return 1
    fi
}

# Execute if called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi