#!/bin/bash
#
# Module: Shell Environment Configuration
# Purpose: Configure shell aliases, prompt, editor, and tmux settings
#

# Module configuration
readonly MODULE_NAME="shell-env"
readonly PROFILE_FILE="/etc/profile.d/homelab-shell.sh"
readonly TMUX_CONFIG="/etc/tmux.conf"
readonly TMUX_CONFIG_BACKUP="${TMUX_CONFIG}.bak"

# Create shell environment configuration
create_shell_config() {
    log_info "Creating shell environment configuration"

    cat > "$PROFILE_FILE" << 'EOF'
#!/bin/bash
#
# Homelab Platform - Shell Environment Configuration
# Generated by baseline initialization script
#

# 颜色定义
export LS_COLORS='di=1;34:ln=1;36:so=1;35:pi=1;33:ex=1;32:bd=1;33:cd=1;33:su=1;31:sg=1;31:tw=1;34:ow=1;34'

# 常用别名 (Common aliases)
alias ll='ls -alF --color=auto'
alias la='ls -A --color=auto'
alias l='ls -CF --color=auto'
alias ls='ls --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# grep 颜色支持
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# 安全别名
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# 系统信息别名
alias df='df -h'
alias du='du -h'
alias free='free -h'
alias ps='ps aux'

# 网络工具别名
alias ports='netstat -tulanp'
alias ping='ping -c 5'

# 设置默认编辑器
export EDITOR=vim
export VISUAL=vim

# 历史记录配置
export HISTSIZE=10000
export HISTFILESIZE=20000
export HISTCONTROL=ignoredups:erasedups
export HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S "

# 彩色提示符 (Colorful prompt)
if [ "$EUID" -eq 0 ]; then
    # Root用户红色提示符
    export PS1='\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]# '
else
    # 普通用户绿色提示符
    export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$ '
fi

# 启用bash补全
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# tmux 自动启动配置 (可选)
# if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
#     exec tmux
# fi
EOF

    chmod 644 "$PROFILE_FILE"
    log_success "Created shell configuration: $PROFILE_FILE"
}

# Configure tmux with mouse support
configure_tmux() {
    log_info "Configuring tmux with mouse support"

    # Backup existing tmux config if it exists
    if [[ -f "$TMUX_CONFIG" ]] && [[ ! -f "$TMUX_CONFIG_BACKUP" ]]; then
        log_info "Backing up existing tmux configuration"
        cp "$TMUX_CONFIG" "$TMUX_CONFIG_BACKUP"
    fi

    cat > "$TMUX_CONFIG" << 'EOF'
# Homelab Platform - tmux Configuration
# Generated by baseline initialization script

# 启用鼠标支持 (Enable mouse support)
set -g mouse on

# 设置默认终端模式为256色
set -g default-terminal "screen-256color"

# 设置前缀键为 Ctrl-a (可选，默认是 Ctrl-b)
# set -g prefix C-a
# unbind C-b
# bind C-a send-prefix

# 窗格分割快捷键
bind | split-window -h
bind - split-window -v

# 窗格切换快捷键 (Vim风格)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 窗格大小调整
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# 启用活动监控
setw -g monitor-activity on
set -g visual-activity on

# 设置状态栏
set -g status-bg colour235
set -g status-fg colour136
set -g status-left-length 20
set -g status-left '#[fg=colour166]#H #[fg=colour136]'
set -g status-right '#[fg=colour166]%Y-%m-%d %H:%M'

# 窗口状态栏颜色
setw -g window-status-current-style fg=colour166,bg=colour235,bold
setw -g window-status-style fg=colour244,bg=colour235

# 复制模式使用vi键绑定
setw -g mode-keys vi

# 历史记录行数
set -g history-limit 10000

# 窗口和窗格编号从1开始
set -g base-index 1
setw -g pane-base-index 1

# 自动重新编号窗口
set -g renumber-windows on

# 减少延迟时间
set -sg escape-time 1

# 重新加载配置文件的快捷键
bind r source-file /etc/tmux.conf \; display "tmux配置已重新加载!"
EOF

    chmod 644 "$TMUX_CONFIG"
    log_success "Created tmux configuration: $TMUX_CONFIG"
}

# Test shell configuration
test_shell_config() {
    log_info "Testing shell configuration"

    # Check if profile file exists and is readable
    if [[ -f "$PROFILE_FILE" ]] && [[ -r "$PROFILE_FILE" ]]; then
        log_success "Shell configuration file is accessible"
    else
        log_error "Shell configuration file is not accessible"
        return 1
    fi

    # Test if aliases are defined (source the file in a subshell)
    if (
        source "$PROFILE_FILE" 2>/dev/null
        type ll >/dev/null 2>&1 && type la >/dev/null 2>&1
    ); then
        log_success "Shell aliases are properly defined"
    else
        log_error "Shell aliases are not properly defined"
        return 1
    fi

    return 0
}

# Test tmux configuration
test_tmux_config() {
    log_info "Testing tmux configuration"

    if [[ -f "$TMUX_CONFIG" ]] && [[ -r "$TMUX_CONFIG" ]]; then
        log_success "tmux configuration file is accessible"
    else
        log_error "tmux configuration file is not accessible"
        return 1
    fi

    # Test tmux config syntax
    if command -v tmux >/dev/null 2>&1; then
        # Capture exit code properly
        tmux -f "$TMUX_CONFIG" list-sessions >/dev/null 2>&1
        local tmux_exit_code=$?
        if [[ $tmux_exit_code -eq 0 ]] || [[ $tmux_exit_code -eq 1 ]]; then
            # Exit code 0 = sessions exist, exit code 1 = no sessions exist (both are valid)
            log_success "tmux configuration syntax is valid"
        else
            log_error "tmux configuration has syntax errors"
            return 1
        fi
    else
        log_warn "tmux not installed, skipping configuration test"
    fi

    return 0
}

# Check if shell environment is already configured
is_shell_configured() {
    [[ -f "$PROFILE_FILE" ]] && grep -q "Homelab Platform" "$PROFILE_FILE"
}

# Check if tmux is already configured
is_tmux_configured() {
    [[ -f "$TMUX_CONFIG" ]] && grep -q "Homelab Platform" "$TMUX_CONFIG"
}

# Main module execution
main() {
    log_info "Starting shell environment configuration"

    local config_updated=false

    # Configure shell environment
    if is_shell_configured; then
        log_info "Shell environment already configured"
    else
        create_shell_config
        config_updated=true
    fi

    # Configure tmux
    if is_tmux_configured; then
        log_info "tmux already configured"
    else
        configure_tmux
        config_updated=true
    fi

    # Test configurations
    if ! test_shell_config; then
        log_error "Shell configuration test failed"
        return 1
    fi

    if ! test_tmux_config; then
        log_error "tmux configuration test failed"
        return 1
    fi

    if [[ "$config_updated" == true ]]; then
        log_success "Shell environment configuration completed successfully"
        log_info "Changes will take effect after re-login or sourcing profile"
    else
        log_info "Shell environment already properly configured"
    fi

    return 0
}

# Execute if called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi