#!/bin/bash
#
# Module: MOTD (Message of the Day) Configuration
# Purpose: Create custom MOTD with hostname, IP, zone detection, load, memory, and disk info
#

# Module configuration
readonly MODULE_NAME="motd"
readonly MOTD_SCRIPT="/etc/update-motd.d/10-homelab-info"
readonly MOTD_BACKUP_DIR="/etc/update-motd.d/disabled"

# Zone detection based on IP ranges (根据IP段自动检测Zone)
detect_zone() {
    local ip="$1"

    # 定义Zone映射 (根据homelab网络规划)
    case "$ip" in
        10.0.1.*) echo "DMZ" ;;
        10.0.2.*) echo "Services" ;;
        10.0.3.*) echo "Storage" ;;
        10.0.4.*) echo "Management" ;;
        10.0.10.*) echo "Development" ;;
        10.0.20.*) echo "Testing" ;;
        192.168.1.*) echo "LAN" ;;
        192.168.100.*) echo "Guest" ;;
        172.16.*) echo "Docker" ;;
        *) echo "Unknown" ;;
    esac
}

# Get primary IP address
get_primary_ip() {
    # 获取默认路由接口的IP地址
    local interface=$(ip route | grep default | head -1 | awk '{print $5}')
    if [[ -n "$interface" ]]; then
        ip addr show "$interface" | grep 'inet ' | head -1 | awk '{print $2}' | cut -d'/' -f1
    else
        echo "127.0.0.1"
    fi
}

# Get system load average
get_load_average() {
    local load=$(uptime | awk -F'load average:' '{print $2}' | sed 's/^ *//')
    echo "$load"
}

# Get memory usage
get_memory_usage() {
    local mem_info=$(free -h | grep '^Mem:')
    local total=$(echo "$mem_info" | awk '{print $2}')
    local used=$(echo "$mem_info" | awk '{print $3}')
    local available=$(echo "$mem_info" | awk '{print $7}')
    echo "Used: $used / Total: $total (Available: $available)"
}

# Get disk usage for root filesystem
get_disk_usage() {
    local disk_info=$(df -h / | tail -1)
    local used=$(echo "$disk_info" | awk '{print $3}')
    local total=$(echo "$disk_info" | awk '{print $2}')
    local percent=$(echo "$disk_info" | awk '{print $5}')
    echo "Used: $used / Total: $total ($percent)"
}

# Get system uptime
get_uptime() {
    uptime -p | sed 's/up //'
}

# Create MOTD script
create_motd_script() {
    log_info "Creating custom MOTD script"

    cat > "$MOTD_SCRIPT" << 'EOF'
#!/bin/bash
#
# Homelab Platform - Custom MOTD
# Generated by baseline initialization script
#

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

# Zone detection function
detect_zone() {
    local ip="$1"
    case "$ip" in
        10.0.1.*) echo "DMZ" ;;
        10.0.2.*) echo "Services" ;;
        10.0.3.*) echo "Storage" ;;
        10.0.4.*) echo "Management" ;;
        10.0.10.*) echo "Development" ;;
        10.0.20.*) echo "Testing" ;;
        192.168.1.*) echo "LAN" ;;
        192.168.100.*) echo "Guest" ;;
        172.16.*) echo "Docker" ;;
        *) echo "Unknown" ;;
    esac
}

# Get primary IP
get_primary_ip() {
    local interface=$(ip route | grep default | head -1 | awk '{print $5}' 2>/dev/null)
    if [[ -n "$interface" ]]; then
        ip addr show "$interface" 2>/dev/null | grep 'inet ' | head -1 | awk '{print $2}' | cut -d'/' -f1
    else
        echo "127.0.0.1"
    fi
}

# System information
HOSTNAME=$(hostname)
PRIMARY_IP=$(get_primary_ip)
ZONE=$(detect_zone "$PRIMARY_IP")
UPTIME=$(uptime -p 2>/dev/null | sed 's/up //' || echo "unknown")
LOAD=$(uptime | awk -F'load average:' '{print $2}' | sed 's/^ *//' 2>/dev/null || echo "unknown")

# Memory info
MEM_INFO=$(free -h 2>/dev/null | grep '^Mem:' || echo "Mem: unknown unknown unknown unknown unknown unknown unknown")
MEM_TOTAL=$(echo "$MEM_INFO" | awk '{print $2}')
MEM_USED=$(echo "$MEM_INFO" | awk '{print $3}')
MEM_AVAILABLE=$(echo "$MEM_INFO" | awk '{print $7}')

# Disk info
DISK_INFO=$(df -h / 2>/dev/null | tail -1 || echo "/ unknown unknown unknown unknown unknown")
DISK_TOTAL=$(echo "$DISK_INFO" | awk '{print $2}')
DISK_USED=$(echo "$DISK_INFO" | awk '{print $3}')
DISK_PERCENT=$(echo "$DISK_INFO" | awk '{print $5}')

# OS info
OS_INFO=$(lsb_release -d 2>/dev/null | cut -f2 || echo "Unknown Linux")
KERNEL=$(uname -r 2>/dev/null || echo "unknown")

# Print MOTD
echo
echo -e "${WHITE}╔══════════════════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${WHITE}║                          ${CYAN}🏠 Homelab Platform${WHITE}                              ║${NC}"
echo -e "${WHITE}╠══════════════════════════════════════════════════════════════════════════════╣${NC}"
echo -e "${WHITE}║ ${YELLOW}Hostname:${NC} ${GREEN}$HOSTNAME${WHITE}                                                    ║${NC}"
echo -e "${WHITE}║ ${YELLOW}IP Address:${NC} ${GREEN}$PRIMARY_IP${WHITE} (Zone: ${PURPLE}$ZONE${WHITE})                              ║${NC}"
echo -e "${WHITE}║ ${YELLOW}OS:${NC} $OS_INFO                                           ║${NC}"
echo -e "${WHITE}║ ${YELLOW}Kernel:${NC} $KERNEL                                                ║${NC}"
echo -e "${WHITE}╠══════════════════════════════════════════════════════════════════════════════╣${NC}"
echo -e "${WHITE}║ ${YELLOW}Uptime:${NC} $UPTIME                                                ║${NC}"
echo -e "${WHITE}║ ${YELLOW}Load Average:${NC} $LOAD                                           ║${NC}"
echo -e "${WHITE}║ ${YELLOW}Memory:${NC} Used: ${GREEN}$MEM_USED${NC} / Total: ${BLUE}$MEM_TOTAL${NC} (Available: ${GREEN}$MEM_AVAILABLE${NC})    ║${NC}"
echo -e "${WHITE}║ ${YELLOW}Disk (/):${NC} Used: ${GREEN}$DISK_USED${NC} / Total: ${BLUE}$DISK_TOTAL${NC} (${RED}$DISK_PERCENT${NC})                ║${NC}"
echo -e "${WHITE}╚══════════════════════════════════════════════════════════════════════════════╝${NC}"
echo

# Show any important system messages
if [[ -f /var/run/reboot-required ]]; then
    echo -e "${RED}⚠️  System reboot required${NC}"
    echo
fi

# Show last login info (if available)
if command -v last >/dev/null 2>&1; then
    echo -e "${YELLOW}Last login:${NC}"
    last -n 3 -a | head -3
    echo
fi
EOF

    chmod +x "$MOTD_SCRIPT"
    log_success "Created MOTD script: $MOTD_SCRIPT"
}

# Disable default MOTD scripts that might conflict
disable_default_motd() {
    log_info "Managing default MOTD scripts"

    # Create backup directory
    mkdir -p "$MOTD_BACKUP_DIR"

    # List of default MOTD scripts that might conflict
    local default_scripts=(
        "/etc/update-motd.d/00-header"
        "/etc/update-motd.d/10-help-text"
        "/etc/update-motd.d/50-motd-news"
        "/etc/update-motd.d/80-esm"
        "/etc/update-motd.d/90-updates-available"
        "/etc/update-motd.d/95-hwe-eol"
    )

    for script in "${default_scripts[@]}"; do
        if [[ -f "$script" ]]; then
            local script_name=$(basename "$script")
            if [[ ! -f "$MOTD_BACKUP_DIR/$script_name" ]]; then
                log_info "Disabling default MOTD script: $script_name"
                mv "$script" "$MOTD_BACKUP_DIR/"
            fi
        fi
    done

    # Disable motd-news if it exists
    if [[ -f "/etc/default/motd-news" ]]; then
        sed -i 's/ENABLED=1/ENABLED=0/' /etc/default/motd-news 2>/dev/null || true
    fi
}

# Test MOTD configuration
test_motd() {
    log_info "Testing MOTD configuration"

    if [[ -f "$MOTD_SCRIPT" ]] && [[ -x "$MOTD_SCRIPT" ]]; then
        log_success "MOTD script is executable"
    else
        log_error "MOTD script is not executable"
        return 1
    fi

    # Test MOTD script execution
    if "$MOTD_SCRIPT" >/dev/null 2>&1; then
        log_success "MOTD script executes without errors"
    else
        log_error "MOTD script has execution errors"
        return 1
    fi

    # Update MOTD cache
    if command -v update-motd >/dev/null 2>&1; then
        update-motd >/dev/null 2>&1 || true
        log_success "MOTD cache updated"
    fi

    return 0
}

# Check if MOTD is already configured
is_motd_configured() {
    [[ -f "$MOTD_SCRIPT" ]] && grep -q "Homelab Platform" "$MOTD_SCRIPT"
}

# Main module execution
main() {
    log_info "Starting MOTD configuration"

    if is_motd_configured; then
        log_info "MOTD already configured"
        return 0
    fi

    # Create custom MOTD script
    create_motd_script

    # Disable conflicting default MOTD scripts
    disable_default_motd

    # Test MOTD configuration
    if test_motd; then
        log_success "MOTD configuration completed successfully"
        log_info "Custom MOTD will be displayed on next login"
    else
        log_error "MOTD configuration test failed"
        return 1
    fi

    return 0
}

# Execute if called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi