#!/bin/bash
#
# Module: System Configuration
# Purpose: Configure timezone, locale, npm registry, NTP, journald, and sysctl settings
#

# Module configuration
readonly MODULE_NAME="system"
readonly TIMEZONE="Asia/Shanghai"
readonly LOCALE="en_US.UTF-8"
readonly NPM_CONFIG="/etc/npmrc"
readonly NPM_REGISTRY="https://registry.npmmirror.com"
readonly TIMESYNCD_CONFIG="/etc/systemd/timesyncd.conf"
readonly JOURNALD_CONFIG="/etc/systemd/journald.conf.d/homelab.conf"
readonly SYSCTL_CONFIG="/etc/sysctl.d/99-homelab.conf"

# Configure timezone
configure_timezone() {
    log_info "Configuring timezone to $TIMEZONE"

    local current_timezone=$(timedatectl show --property=Timezone --value 2>/dev/null || echo "unknown")

    if [[ "$current_timezone" == "$TIMEZONE" ]]; then
        log_info "Timezone already set to $TIMEZONE"
        return 0
    fi

    if timedatectl set-timezone "$TIMEZONE" 2>/dev/null; then
        log_success "Timezone set to $TIMEZONE"
        return 0
    else
        log_error "Failed to set timezone to $TIMEZONE"
        return 1
    fi
}

# Configure locale
configure_locale() {
    log_info "Configuring locale to $LOCALE"

    # Check if locale is already generated
    if locale -a 2>/dev/null | grep -q "^${LOCALE}$"; then
        log_info "Locale $LOCALE already available"
    else
        log_info "Generating locale $LOCALE"

        # Uncomment locale in /etc/locale.gen
        if [[ -f /etc/locale.gen ]]; then
            sed -i "s/^# *${LOCALE}/${LOCALE}/" /etc/locale.gen
            locale-gen >/dev/null 2>&1
        fi
    fi

    # Set system locale
    if update-locale LANG="$LOCALE" >/dev/null 2>&1; then
        log_success "System locale configured to $LOCALE"
        return 0
    else
        log_error "Failed to configure system locale"
        return 1
    fi
}

# Configure npm registry
configure_npm_registry() {
    log_info "Configuring npm registry to use Alibaba mirror"

    # Check if npm config already exists and is correct
    if [[ -f "$NPM_CONFIG" ]] && grep -q "registry=$NPM_REGISTRY" "$NPM_CONFIG"; then
        log_info "npm registry already configured"
        return 0
    fi

    # Create or update npm config
    cat > "$NPM_CONFIG" << EOF
# Homelab Platform - npm Configuration
# Generated by baseline initialization script
# $(date)

# 使用阿里云镜像源
registry=$NPM_REGISTRY

# 其他优化配置
# 禁用进度条以减少日志噪音
progress=false

# 设置缓存目录
cache=/var/cache/npm

# 设置超时时间
timeout=60000

# 禁用更新检查
update-notifier=false
EOF

    chmod 644 "$NPM_CONFIG"
    log_success "npm registry configured to use Alibaba mirror"

    # Verify configuration
    if command -v npm >/dev/null 2>&1; then
        local current_registry=$(npm config get registry 2>/dev/null || echo "unknown")
        if [[ "$current_registry" == "$NPM_REGISTRY" ]]; then
            log_success "npm registry verification successful"
        else
            log_warn "npm registry verification failed (current: $current_registry)"
        fi
    else
        log_info "npm not installed, configuration will take effect when npm is installed"
    fi

    return 0
}

# Configure NTP with Chinese servers
configure_ntp() {
    log_info "Configuring NTP with Chinese servers"

    # Create systemd-timesyncd configuration
    mkdir -p "$(dirname "$TIMESYNCD_CONFIG")"

    cat > "$TIMESYNCD_CONFIG" << EOF
# Homelab Platform - NTP Configuration
# Generated by baseline initialization script
# $(date)

[Time]
# 中国NTP服务器
NTP=ntp.aliyun.com ntp.tencent.com time.pool.aliyun.com
FallbackNTP=pool.ntp.org time.nist.gov

# 设置时区信息
#Timezone=$TIMEZONE

# 启用网络时间同步
#PollIntervalMinSec=32
#PollIntervalMaxSec=2048
EOF

    chmod 644 "$TIMESYNCD_CONFIG"

    # Enable and restart systemd-timesyncd
    if systemctl enable systemd-timesyncd >/dev/null 2>&1 && systemctl restart systemd-timesyncd >/dev/null 2>&1; then
        log_success "NTP configuration completed and service restarted"

        # Wait a moment and check status
        sleep 2
        if systemctl is-active systemd-timesyncd >/dev/null 2>&1; then
            log_success "systemd-timesyncd is running"
        else
            log_warn "systemd-timesyncd may not be running properly"
        fi
    else
        log_error "Failed to configure NTP service"
        return 1
    fi

    return 0
}

# Configure journald
configure_journald() {
    log_info "Configuring journald log limits"

    # Create journald configuration directory
    mkdir -p "$(dirname "$JOURNALD_CONFIG")"

    cat > "$JOURNALD_CONFIG" << EOF
# Homelab Platform - Journald Configuration
# Generated by baseline initialization script
# $(date)

[Journal]
# 限制日志大小为200MB
SystemMaxUse=200M
SystemKeepFree=1G
SystemMaxFileSize=50M

# 保留30天的日志
MaxRetentionSec=30d

# 压缩日志
Compress=yes

# 转发到syslog (可选)
#ForwardToSyslog=no

# 存储模式
Storage=persistent
EOF

    chmod 644 "$JOURNALD_CONFIG"

    # Restart systemd-journald to apply changes
    if systemctl restart systemd-journald >/dev/null 2>&1; then
        log_success "journald configuration applied and service restarted"
    else
        log_error "Failed to restart journald service"
        return 1
    fi

    return 0
}

# Configure sysctl parameters
configure_sysctl() {
    log_info "Configuring sysctl parameters"

    cat > "$SYSCTL_CONFIG" << EOF
# Homelab Platform - Sysctl Configuration
# Generated by baseline initialization script
# $(date)

# 内存管理优化
# 降低swap使用倾向，优先使用物理内存
vm.swappiness=10

# 网络优化
# 增加网络缓冲区大小
net.core.rmem_default = 262144
net.core.rmem_max = 16777216
net.core.wmem_default = 262144
net.core.wmem_max = 16777216

# TCP优化
net.ipv4.tcp_rmem = 4096 65536 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216

# 文件系统优化
# 增加文件句柄限制
fs.file-max = 65536

# 内核安全加固
# 禁用IP转发 (如果不需要路由功能)
net.ipv4.ip_forward = 0
net.ipv6.conf.all.forwarding = 0

# 防止IP欺骗
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# 忽略ICMP重定向
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# 忽略发送重定向
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
EOF

    chmod 644 "$SYSCTL_CONFIG"

    # Apply sysctl configuration
    if sysctl -p "$SYSCTL_CONFIG" >/dev/null 2>&1; then
        log_success "sysctl configuration applied"
    else
        log_error "Failed to apply sysctl configuration"
        return 1
    fi

    return 0
}

# Test system configurations
test_system_config() {
    log_info "Testing system configurations"

    # Test timezone
    local current_timezone=$(timedatectl show --property=Timezone --value 2>/dev/null)
    if [[ "$current_timezone" == "$TIMEZONE" ]]; then
        log_success "Timezone verification: $TIMEZONE"
    else
        log_warn "Timezone verification failed (current: $current_timezone)"
    fi

    # Test locale
    if locale | grep -q "LANG=$LOCALE"; then
        log_success "Locale verification: $LOCALE"
    else
        log_warn "Locale verification failed"
    fi

    # Test npm config
    if [[ -f "$NPM_CONFIG" ]] && grep -q "$NPM_REGISTRY" "$NPM_CONFIG"; then
        log_success "npm configuration verification successful"
    else
        log_warn "npm configuration verification failed"
    fi

    # Test NTP
    if systemctl is-active systemd-timesyncd >/dev/null 2>&1; then
        log_success "NTP service verification successful"
    else
        log_warn "NTP service verification failed"
    fi

    # Test journald config
    if [[ -f "$JOURNALD_CONFIG" ]]; then
        log_success "journald configuration file exists"
    else
        log_warn "journald configuration file missing"
    fi

    # Test sysctl config
    if [[ -f "$SYSCTL_CONFIG" ]]; then
        local swappiness=$(sysctl -n vm.swappiness 2>/dev/null || echo "unknown")
        if [[ "$swappiness" == "10" ]]; then
            log_success "sysctl verification: vm.swappiness=10"
        else
            log_warn "sysctl verification failed (vm.swappiness=$swappiness)"
        fi
    else
        log_warn "sysctl configuration file missing"
    fi

    return 0
}

# Check if system is already configured
is_system_configured() {
    local timezone_ok=false
    local npm_ok=false
    local ntp_ok=false
    local journald_ok=false
    local sysctl_ok=false

    # Check timezone
    local current_timezone=$(timedatectl show --property=Timezone --value 2>/dev/null)
    [[ "$current_timezone" == "$TIMEZONE" ]] && timezone_ok=true

    # Check npm config
    [[ -f "$NPM_CONFIG" ]] && grep -q "$NPM_REGISTRY" "$NPM_CONFIG" && npm_ok=true

    # Check NTP config
    [[ -f "$TIMESYNCD_CONFIG" ]] && grep -q "ntp.aliyun.com" "$TIMESYNCD_CONFIG" && ntp_ok=true

    # Check journald config
    [[ -f "$JOURNALD_CONFIG" ]] && grep -q "SystemMaxUse=200M" "$JOURNALD_CONFIG" && journald_ok=true

    # Check sysctl config
    [[ -f "$SYSCTL_CONFIG" ]] && grep -q "vm.swappiness=10" "$SYSCTL_CONFIG" && sysctl_ok=true

    # Return true only if all are configured
    $timezone_ok && $npm_ok && $ntp_ok && $journald_ok && $sysctl_ok
}

# Main module execution
main() {
    log_info "Starting system configuration"

    if is_system_configured; then
        log_info "System already configured"
        test_system_config
        return 0
    fi

    local failed_configs=()

    # Configure timezone
    if ! configure_timezone; then
        failed_configs+=("timezone")
    fi

    # Configure locale
    if ! configure_locale; then
        failed_configs+=("locale")
    fi

    # Configure npm registry
    if ! configure_npm_registry; then
        failed_configs+=("npm")
    fi

    # Configure NTP
    if ! configure_ntp; then
        failed_configs+=("ntp")
    fi

    # Configure journald
    if ! configure_journald; then
        failed_configs+=("journald")
    fi

    # Configure sysctl
    if ! configure_sysctl; then
        failed_configs+=("sysctl")
    fi

    # Test configurations
    test_system_config

    if [[ ${#failed_configs[@]} -eq 0 ]]; then
        log_success "System configuration completed successfully"
        log_info "Some changes may require a reboot to take full effect"
    else
        log_warn "Some system configurations failed: ${failed_configs[*]}"
        return 1
    fi

    return 0
}

# Execute if called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi