#!/bin/bash
#
# Module: Security Configuration
# Purpose: Configure unattended-upgrades for security updates only
#

# Module configuration
readonly MODULE_NAME="security"
readonly UNATTENDED_UPGRADES_CONFIG="/etc/apt/apt.conf.d/50unattended-upgrades"
readonly AUTO_UPGRADES_CONFIG="/etc/apt/apt.conf.d/20auto-upgrades"
readonly UNATTENDED_UPGRADES_BACKUP="${UNATTENDED_UPGRADES_CONFIG}.bak"
readonly AUTO_UPGRADES_BACKUP="${AUTO_UPGRADES_CONFIG}.bak"

# Install unattended-upgrades package
install_unattended_upgrades() {
    log_info "Installing unattended-upgrades package"

    if dpkg -l unattended-upgrades 2>/dev/null | grep -q "^ii"; then
        log_info "unattended-upgrades already installed"
        return 0
    fi

    if DEBIAN_FRONTEND=noninteractive apt-get install -y unattended-upgrades >/dev/null 2>&1; then
        log_success "unattended-upgrades installed successfully"
        return 0
    else
        log_error "Failed to install unattended-upgrades"
        return 1
    fi
}

# Configure unattended-upgrades
configure_unattended_upgrades() {
    log_info "Configuring unattended-upgrades for security updates only"

    # Backup existing configuration
    if [[ -f "$UNATTENDED_UPGRADES_CONFIG" ]] && [[ ! -f "$UNATTENDED_UPGRADES_BACKUP" ]]; then
        log_info "Backing up existing unattended-upgrades configuration"
        cp "$UNATTENDED_UPGRADES_CONFIG" "$UNATTENDED_UPGRADES_BACKUP"
    fi

    # Get Debian codename
    local codename=$(lsb_release -sc 2>/dev/null || echo "bookworm")

    cat > "$UNATTENDED_UPGRADES_CONFIG" << EOF
// Homelab Platform - Unattended Upgrades Configuration
// Generated by baseline initialization script
// $(date)

// 自动升级的软件包来源 (仅安全更新)
Unattended-Upgrade::Allowed-Origins {
    "\${distro_id}:\${distro_codename}";
    "\${distro_id}:\${distro_codename}-security";
    // 注释掉常规更新，只保留安全更新
    // "\${distro_id}ESMApps:\${distro_codename}-apps-security";
    // "\${distro_id}ESM:\${distro_codename}-infra-security";
};

// 软件包黑名单 (不自动升级的包)
Unattended-Upgrade::Package-Blacklist {
    // 内核相关包需要手动升级
    "linux-image*";
    "linux-headers*";
    "linux-modules*";
    "linux-generic*";

    // 数据库相关包需要手动升级
    "mysql*";
    "postgresql*";
    "mariadb*";

    // 容器运行时需要手动升级
    "docker*";
    "containerd*";
    "kubernetes*";
    "k3s*";

    // Web服务器需要手动升级
    "nginx*";
    "apache2*";
};

// 自动移除不需要的依赖包
Unattended-Upgrade::Remove-Unused-Dependencies "true";

// 自动移除新的未使用的内核包
Unattended-Upgrade::Remove-New-Unused-Dependencies "true";

// 自动移除未使用的内核包
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";

// 升级前自动清理 /boot 目录
Unattended-Upgrade::Skip-Updates-On-Metered-Connections "true";

// 邮件通知配置 (暂时禁用)
// Unattended-Upgrade::Mail "root";
// Unattended-Upgrade::MailOnlyOnError "true";

// 日志配置
Unattended-Upgrade::SyslogEnable "true";
Unattended-Upgrade::SyslogFacility "daemon";

// 升级时间窗口 (避免业务高峰期)
Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::Automatic-Reboot-WithUsers "false";
Unattended-Upgrade::Automatic-Reboot-Time "02:00";

// 下载升级包但不安装 (可选，用于测试)
// Unattended-Upgrade::Download-Upgradeable-Packages "true";
// Unattended-Upgrade::AutoFixInterruptedDpkg "true";

// 最小升级间隔 (天)
Unattended-Upgrade::MinimalSteps "true";

// 安装升级包时的详细输出
Unattended-Upgrade::InstallOnShutdown "false";

// 保持系统运行，避免不必要的重启
Unattended-Upgrade::Keep-Debs-After-Install "false";

// dpkg 选项
Dpkg::Options {
   "--force-confdef";
   "--force-confold";
};

// 升级完成后的清理工作
Unattended-Upgrade::OnlyOnACPower "false";
EOF

    chmod 644 "$UNATTENDED_UPGRADES_CONFIG"
    log_success "unattended-upgrades configuration created"
}

# Configure auto-upgrades
configure_auto_upgrades() {
    log_info "Configuring automatic upgrades schedule"

    # Backup existing configuration
    if [[ -f "$AUTO_UPGRADES_CONFIG" ]] && [[ ! -f "$AUTO_UPGRADES_BACKUP" ]]; then
        log_info "Backing up existing auto-upgrades configuration"
        cp "$AUTO_UPGRADES_CONFIG" "$AUTO_UPGRADES_BACKUP"
    fi

    cat > "$AUTO_UPGRADES_CONFIG" << EOF
// Homelab Platform - Auto Upgrades Configuration
// Generated by baseline initialization script
// $(date)

// 启用自动更新包列表 (每天)
APT::Periodic::Update-Package-Lists "1";

// 启用自动下载可升级包 (每天)
APT::Periodic::Download-Upgradeable-Packages "1";

// 启用自动安装安全更新 (每天)
APT::Periodic::Unattended-Upgrade "1";

// 自动清理下载的包缓存 (每7天)
APT::Periodic::AutocleanInterval "7";

// 详细日志记录
APT::Periodic::Verbose "2";
EOF

    chmod 644 "$AUTO_UPGRADES_CONFIG"
    log_success "auto-upgrades configuration created"
}

# Test unattended-upgrades configuration
test_unattended_upgrades() {
    log_info "Testing unattended-upgrades configuration"

    # Check if service is enabled
    if systemctl is-enabled unattended-upgrades >/dev/null 2>&1; then
        log_success "unattended-upgrades service is enabled"
    else
        log_warn "unattended-upgrades service is not enabled"
    fi

    # Check if service is active
    if systemctl is-active unattended-upgrades >/dev/null 2>&1; then
        log_success "unattended-upgrades service is active"
    else
        log_warn "unattended-upgrades service is not active"
    fi

    # Test configuration syntax
    if unattended-upgrade --dry-run >/dev/null 2>&1; then
        log_success "unattended-upgrades configuration syntax is valid"
    else
        log_error "unattended-upgrades configuration has syntax errors"
        return 1
    fi

    # Check timer status
    if systemctl is-active apt-daily.timer >/dev/null 2>&1; then
        log_success "apt-daily.timer is active"
    else
        log_warn "apt-daily.timer is not active"
    fi

    if systemctl is-active apt-daily-upgrade.timer >/dev/null 2>&1; then
        log_success "apt-daily-upgrade.timer is active"
    else
        log_warn "apt-daily-upgrade.timer is not active"
    fi

    return 0
}

# Enable and start unattended-upgrades service
enable_unattended_upgrades() {
    log_info "Enabling unattended-upgrades service"

    if systemctl enable unattended-upgrades >/dev/null 2>&1; then
        log_success "unattended-upgrades service enabled"
    else
        log_error "Failed to enable unattended-upgrades service"
        return 1
    fi

    if systemctl start unattended-upgrades >/dev/null 2>&1; then
        log_success "unattended-upgrades service started"
    else
        log_warn "Failed to start unattended-upgrades service (may be normal)"
    fi

    # Enable and start related timers
    systemctl enable apt-daily.timer >/dev/null 2>&1
    systemctl enable apt-daily-upgrade.timer >/dev/null 2>&1
    systemctl start apt-daily.timer >/dev/null 2>&1
    systemctl start apt-daily-upgrade.timer >/dev/null 2>&1

    return 0
}

# Show security status
show_security_status() {
    log_info "Security configuration status:"

    # Show next scheduled runs
    if command -v systemctl >/dev/null 2>&1; then
        echo "  Next apt update: $(systemctl list-timers apt-daily.timer --no-pager --no-legend | awk '{print $1, $2}' 2>/dev/null || echo 'unknown')"
        echo "  Next apt upgrade: $(systemctl list-timers apt-daily-upgrade.timer --no-pager --no-legend | awk '{print $1, $2}' 2>/dev/null || echo 'unknown')"
    fi

    # Show available security updates
    if command -v apt >/dev/null 2>&1; then
        local security_updates=$(apt list --upgradable 2>/dev/null | grep -c security || echo "0")
        echo "  Available security updates: $security_updates"
    fi
}

# Check if security is already configured
is_security_configured() {
    [[ -f "$UNATTENDED_UPGRADES_CONFIG" ]] && grep -q "Homelab Platform" "$UNATTENDED_UPGRADES_CONFIG" && \
    [[ -f "$AUTO_UPGRADES_CONFIG" ]] && grep -q "Homelab Platform" "$AUTO_UPGRADES_CONFIG"
}

# Main module execution
main() {
    log_info "Starting security configuration"

    if is_security_configured; then
        log_info "Security already configured"
        test_unattended_upgrades
        show_security_status
        return 0
    fi

    # Install unattended-upgrades package
    if ! install_unattended_upgrades; then
        log_error "Failed to install unattended-upgrades package"
        return 1
    fi

    # Configure unattended-upgrades
    if ! configure_unattended_upgrades; then
        log_error "Failed to configure unattended-upgrades"
        return 1
    fi

    # Configure auto-upgrades
    if ! configure_auto_upgrades; then
        log_error "Failed to configure auto-upgrades"
        return 1
    fi

    # Enable and start services
    if ! enable_unattended_upgrades; then
        log_error "Failed to enable unattended-upgrades service"
        return 1
    fi

    # Test configuration
    if ! test_unattended_upgrades; then
        log_error "unattended-upgrades configuration test failed"
        return 1
    fi

    # Show status
    show_security_status

    log_success "Security configuration completed successfully"
    log_info "System will automatically install security updates daily"

    return 0
}

# Execute if called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi